# Site settings
title: Browser Extension Community Group
url: "https://browserext.github.io"

# Build settings
markdown: kramdown

collections:
        minutes:
                output: true
exclude:
        - Gemfile
        - Gemfile.lock
        - README.md
        - scripts
#defaults
defaults:
        -
                scope:
                        type: "pages"
                values:
                        layout: "default"

        -
                scope:
                        path: ""
                        type: minutes
                values:
                        layout: "default"
